apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-sample-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eks-sample-app
  template:
    metadata:
      labels:
        app: eks-sample-app
    spec:
      containers:
        - name: app
          image:593793022607.dkr.ecr.af-south-1.amazonaws.com/eks-sample-app:latest
          ports:
            - containerPort: 3000
