apiVersion: v1
kind: Service
metadata:
  name: eks-sample-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"
spec:
  type: LoadBalancer
  selector:
    app: eks-sample-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
